From a551c1f4b57cb678a9251d6fc7050a7970df3906 Mon Sep 17 00:00:00 2001
From: Tomas Jelinek <tojeline@redhat.com>
Date: Wed, 31 May 2017 07:50:59 +0200
Subject: [PATCH] fix a crash in adding a remote node

... when an id conflict occurs
---
 pcs/lib/commands/cluster.py | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/pcs/lib/commands/cluster.py b/pcs/lib/commands/cluster.py
index 7386e3c..0bafef5 100644
--- a/pcs/lib/commands/cluster.py
+++ b/pcs/lib/commands/cluster.py
@@ -189,7 +189,7 @@ def node_add_remote(
         for report in report_list + list(e.args):
             if report.code != report_codes.ID_ALREADY_EXISTS:
                 unified_report_list.append(report)
-            elif report.info.get["id"] not in already_exists:
+            elif report.info["id"] not in already_exists:
                 unified_report_list.append(report)
                 already_exists.append(report.info["id"])
         report_list = unified_report_list
-- 
1.8.3.1

